apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora2mqtt
spec:
  template:
    spec:
      containers:
        - name: lora2mqtt
          env:
            - name: Hermod__Security__AuthBypass
              value: "true"
            - name: Hermod__Security__VaultRequireHttps
              value: "false"
            - name: LoRa__MockMode
              value: "true"
            - name: Mqtt__Host
              value: "nanomq"
            - name: Mqtt__UseTls
              value: "false"
