mqtt:
  server: mqtt://127.0.0.1:11883
  base_topic: zigbee
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
advanced:
  log_level: info
  log_output:
    - console
  network_key:
    - 113
    - 242
    - 206
    - 149
    - 100
    - 53
    - 15
    - 248
    - 151
    - 152
    - 209
    - 130
    - 199
    - 96
    - 154
    - 227
  pan_id: 48658
  ext_pan_id:
    - 248
    - 107
    - 240
    - 60
    - 213
    - 97
    - 191
    - 112
  channel: 15
frontend:
  enabled: false
homeassistant:
  enabled: false
version: 5
