mqtt:
  server: mqtt://127.0.0.1:11883
  base_topic: zigbee
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
advanced:
  log_level: info
  log_output: [console]
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
  channel: 15
frontend: false
permit_join: false
homeassistant: false
