mqtt:
  server: mqtt://127.0.0.1:11883
  base_topic: zigbee
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
advanced:
  log_level: info
  log_output:
    - console
  network_key:
    - 51
    - 231
    - 185
    - 222
    - 26
    - 254
    - 238
    - 176
    - 86
    - 125
    - 97
    - 12
    - 202
    - 175
    - 142
    - 81
  pan_id: 25653
  ext_pan_id:
    - 92
    - 138
    - 83
    - 61
    - 71
    - 73
    - 36
    - 58
  channel: 15
frontend:
  enabled: false
homeassistant:
  enabled: false
version: 5
devices:
  '<zigbee-ieee>':
    friendly_name: '<zigbee-ieee>'
