mqtt:
  server: mqtt://127.0.0.1:11883
  base_topic: zigbee
serial:
  port: /dev/ttyUSB1
  adapter: ember
  baudrate: 115200
advanced:
  log_level: info
  log_output:
    - console
  network_key:
    - 31
    - 105
    - 152
    - 133
    - 156
    - 31
    - 93
    - 12
    - 81
    - 167
    - 120
    - 226
    - 5
    - 20
    - 88
    - 57
  pan_id: 17521
  ext_pan_id:
    - 49
    - 159
    - 70
    - 27
    - 217
    - 98
    - 120
    - 252
  channel: 15
frontend:
  enabled: false
homeassistant:
  enabled: false
version: 5
