mqtt:
  server: mqtt://127.0.0.1:11883
  base_topic: zigbee
serial:
  port: /dev/ttyUSB1
  adapter: ember
  baudrate: 115200
advanced:
  log_level: info
  log_output:
    - console
  network_key:
    - 26
    - 74
    - 151
    - 69
    - 64
    - 65
    - 204
    - 190
    - 132
    - 210
    - 61
    - 18
    - 235
    - 235
    - 144
    - 68
  pan_id: 429
  ext_pan_id:
    - 41
    - 123
    - 34
    - 16
    - 195
    - 55
    - 103
    - 180
  channel: 15
frontend:
  enabled: false
homeassistant:
  enabled: false
version: 5
